add measure result
knative-sandbox/kperf pull request #25
Opened 2020-12-09 02:05 UTC by qibobo

2020-12-10 02:23 UTC, maximilien requested changes
Missing tests. Left a few suggestions to simplify

2020-12-10 02:23 UTC, maximilien commented on pkg/command/service/measure.go
> +							currentMeasureResult.notReadyCount = currentMeasureResult.notReadyCount + 1
I think you can simplify this with `currentMeasureResult.notReadyCount += 1`

2020-12-10 02:23 UTC, maximilien commented on pkg/command/service/measure.go
> +							currentMeasureResult.notReadyCount = currentMeasureResult.notReadyCount + 1
Same for other statements below...

2020-12-10 02:23 UTC, maximilien commented on pkg/command/service/measure.go
> +						currentMeasureResult.userContrainerStartedSum = currentMeasureResult.userContrainerStartedSum + userContrainerStartedDuration.Seconds()
Same as above to simplify and make it easier to read...

2020-12-10 03:05 UTC, qibobo commented
@maximilien 
Thank you for your comments. @gyohuangxin is working on the ut. I have fixed other comments.

2020-12-10 07:47 UTC, zhanggbj commented on pkg/command/service/measure.go
> +
maybe remove extra new line

2020-12-10 07:49 UTC, zhanggbj approved these changes

2020-12-10 10:46 UTC, zyjiaobj commented on pkg/command/service/common.go
>  	svcRoutesReadyReadySum      float64
Why we have 2 `Ready` in the param name?

2020-12-10 10:47 UTC, zyjiaobj commented on pkg/command/service/common.go
>  	svcRoutesReadyReadySum      float64
As well for `ingressReadyReadySum `.

2020-12-10 10:52 UTC, zyjiaobj commented on pkg/command/service/measure.go
> +				measureFinalResult.ingressLoadBalancerReadySum += workerMeasureResults[i].ingressNetworkConfiguredSum
Shouldn't it be `workerMeasureResults[i].ingressLoadBalancerReadySum`

2020-12-10 11:01 UTC, zyjiaobj commented on pkg/command/service/measure.go
> +				fmt.Printf("    Total: %fs\n", float64(measureFinalResult.revisionReadySum))
Shouldn't it be `measureFinalResult.deploymentCreatedSum`?

2020-12-10 11:02 UTC, zyjiaobj commented on pkg/command/service/measure.go
> +				fmt.Printf("    Average: %fs\n", float64(measureFinalResult.revisionReadySum)/float64(measureFinalResult.readyCount))
Shouldn't it be measureFinalResult.deploymentCreatedSum

2020-12-10 11:37 UTC, zyjiaobj approved these changes
LGTM

2020-12-11 07:20 UTC, zhanggbj commented
/lgtm
/assign @maximilien 
/assign @zyjiaobj 

Thanks @qibobo for the quick fix and @maximilien @zyjiaobj for the code review!
I'll merge it as it is blocking #22 Thanks!

2020-12-11 07:22 UTC, merged