[WIP] Add eventing command to run Knative Eventing scaling tests
knative-sandbox/kperf pull request #71
Opened 2021-04-20 14:40 UTC by aslom

This PR implements kperf eventing subcommand following design discussed in https://github.com/knative-sandbox/kperf/issues/24

Getting close to MVP. Sharing Work-in-progress including docs on how to run current version is described in eventing.md (development notes about building Docker image and local testing are in eventing-dev.md)

Remaining work for MVP:
* prepare: support multiple namespaces 
* measure: factor out and improve event workload generator
* measure: add latency buckets and measuring errors, duplicates
* measure: add printing output to .csv, option to stop measurement command when no changes in metrics after N seconds 
* measure: add missing functionality in one command - currently split outside: start kubectl tunnel(s) to receiver namespaces, start retrieving metrics from tunneled localhost:8001 (8002 ...), deploy driver job 
(alternatively instead of tunnels in background https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls )
* cleanup: for each namespace remove driver jobs and receiver deloyment, pods
* add unit tests
* fix build issues (mod vendoring?)
* fix Kafka receiver blocking for Ctrl-C

2021-04-21 20:12 UTC, maximilien commented on Dockerfile
> +# TODO use hack/build.sh ?
Yes, otherwise remove this TODO

2021-04-21 23:36 UTC, aslom commented
/retest

2021-04-26 15:11 UTC, lionelvillard commented on eventing.md
> +That functionality will be wrapped into `kperf eventing` command in near future.
isn't this already the case?

2021-04-26 15:11 UTC, lionelvillard commented on eventing.md
> +Currently it needs ti be run from command line to dwpeloy test receiver.
nit: dwpeloy -> deploy

2021-04-26 15:11 UTC, lionelvillard commented on eventing.md
> +Determina location of receiver service in Kubernetes namespace:
nit: Determina -> Determine

2021-04-26 15:12 UTC, lionelvillard commented on pkg/command/eventing/clean.go
> +// Copyright 2020 The Knative Authors
2021?

2021-04-26 15:13 UTC, lionelvillard commented on pkg/command/eventing/clean.go
> +	ksvcCleanCommand := &cobra.Command{
better use eventingCleanCommand

2021-04-26 15:13 UTC, lionelvillard commented on pkg/command/eventing/clean.go
> +kperf eventing clean --namespace-prefix testns / --namespace nsname
`/` looks strange here.

2021-04-26 15:14 UTC, lionelvillard commented on pkg/command/eventing/clean.go
> +			fmt.Println("Eventng cleaning called")
nit: `Eventng`-> `Eventing`

2021-04-26 15:15 UTC, lionelvillard commented on pkg/command/eventing/clean.go
> +// Copyright 2020 The Knative Authors
this is actually all over the place

2021-04-26 15:16 UTC, lionelvillard commented on pkg/command/eventing/driver.go
> +	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
no need here. Only main should include it.

2021-04-26 15:16 UTC, lionelvillard commented on pkg/command/eventing/driver.go
> +	ksvcCleanCommand := &cobra.Command{
ksvcCleanCommand -> `eventingCleanCommand`

2021-04-26 15:18 UTC, lionelvillard commented on pkg/command/eventing/prepare.go
> +	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
remove

2021-04-26 15:20 UTC, lionelvillard commented
Added some comments. I made sure it does not break Serving. 

LGTM

2021-04-27 00:13 UTC, maximilien requested changes
Lots and lots of issues. Some small, nits, and larger. Seems like many of the issues have to do with imcomplete code. So perhaps this is not really an MVP but rather an incomplete v1.0.

I would love this to move fast. Perhaps one approach is to submit a real MVP — that is only the parts that are done and create issues for the rest. For instance, only support Kafka and move the rest as issues to be submitted in subsequent PRs.

Also, instead of having a bunch of empty unit tests move these to a issue to be done as future PR. And focus on having e2e tests only for MVP?

Finally, I want to move fast in my reviews, however, long PR mean longer time to review (obvious ;) so perhaps many small PRs (even if they depend on each other is a better approach to move faster?

All that said, many thanks @aslom for getting this done and for your hard work. Truly appreciated. Cheers 🍻

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/kafka_sender.go
> +func sendEvents(plan SendEventsPlan) EventsStats {
Break this down into smaller helper function and that will allow you to improve and better visualize this code compared to the Redis sender and others. Also, makes it easier to debug and review :)

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/null_sender.go
> +	// TODO better golang idiom/conversion?
I think this is fine and idiomatic. Remove TODO

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/redis_sender.go
> +	// Group          string
Remove commented fields

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/redis_sender.go
> +	data := []byte("[\"fruit\", \"orange\"]")
This seems like test data...

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/redis_sender.go
> +		panic(err)
Same as before these panic and logFatal will come back to hunt you when you need to debug. Best just deal with error at first catch with message, return and cascade up to end cleanly

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver/workload_generator.go
> +	values := map[string]string{"id": "1234668888888", "source": "323223232332909090", "type": "dev.knative.eventing.test.scaling", "timestamp": "12929299999992222"}
Why do we have test data in the main code? Shouldn’t these be loaded from config if you need to have some values?

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/driver_test.go
> +
Same as before. What I would do is to create an issue with a list of all the missing tests.

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/eventing.go
> +		Long: `Knative eventing load test and measurement. For example:
Use # comment to separate what the user sees as comment vs code they can cut and paste to try

2021-04-27 00:13 UTC, maximilien commented on pkg/command/eventing/eventing_test.go
> +	// _, _, err := cmd.Find([]string{"prepare"})
Same as before, remove these empty tests and create issue with a TODO list.

If you want to keep this code then move it to a branch. Use github for what’s it good for, organizing your code :)

2021-05-07 16:55 UTC, maximilien commented
Any update on this PR @aslom ?

2021-05-07 17:38 UTC, aslom commented
@maximilien working on code simplification and refactoring - should be ready in few days

2021-05-19 17:09 UTC, maximilien commented
Hi, @aslom any updates on this. Anything I can do to help move this?

2021-06-25 17:41 UTC, maximilien commented
Hi, @aslom any updates on this?

2021-07-02 20:39 UTC, aslom commented
@maximilien I have done lot of testing and improvements and finding kperf eventing very useful in testing - I have changed to PR titleWIP to do indicate there will be restructuring going on

2022-01-24 20:53 UTC, maximilien commented
Hi, @aslom, do we have an update on this?

2022-07-23 01:30 UTC, closed without merging